import random
import datetime

task_list = [
    "Bring your own bag when shopping.",
    "Use a reusable water bottle.",
    "Take a 5 minute shower.",
    "Leave the lights off during the day.",
    "Recycle paper and plastic products.",
    "Choose products with minimal packaging.",
    "Don't charge anything between 10am and 7pm.",
    "Plant a tree.",
    "Go vegetarian for today.",
    "Use public transportation or bike to work.",
    "Buy locally-sourced food.",
    "Lower your thermostat by 2 degrees.",
    "Air dry your clothes instead of using the dryer.",
    "Support a company with sustainable practices.",
    "Compost food waste.",
    "Use a clothesline instead of a dryer.",
    "Take the stairs instead of the elevator.",
    "Choose a reusable coffee cup.",
    "Eat vegan for a day.",
    "Plant a garden or window box.",
    "Use a reusable straw or skip it altogether.",
    "Buy in bulk to reduce packaging waste.",
    "Support local farmers and food co-ops.",
    "Turn off your computer at night.",
    "Choose products made from sustainable materials.",
    "Take a walk or bike ride instead of driving.",
    "Shop at thrift stores or garage sales.",
    "Turn off the water while brushing your teeth.",
    "Donate unwanted items.",
    "Choose natural cleaning products.",
    "Reduce plastic use.",
    "Avoid food waste.",
    "Use a reusable food container.",
    "Choose public transit or carpooling.",
    "Support renewable energy policies.",
    "Avoid disposable products.",
    "Turn off the air conditioning when not at home.",
    "Use a reusable grocery bag.",
    "Take a break from social media and TV.",
    "Opt for paperless billing and digital communication.",
    "Buy recycled or sustainable office supplies.",
    "Participate in a recycling program.",
    "Use a refillable water filter instead of bottled water.",
    "Choose fair trade products.",
    "Use a reusable lunch container.",
    "Choose sustainable seafood options.",
    "Support clean air and water initiatives.",
    "Reduce water usage.",
    "Choose a bike or walk to run errands.",
    "Bring your own reusable utensils.",
    "Choose organic food options.",
    "Avoid single-use plastics.",
    "Choose eco-friendly personal care products.",
    "Support sustainable forestry practices.",
    "Turn off the water while soaping up in the shower.",
    "Buy rechargeable batteries.",
    "Support green space initiatives.",
    "Choose a reusable snack container.",
    "Use a bamboo toothbrush.",
    "Choose biodegradable or compostable products.",
    "Support environmental education programs.",
    "Choose a sustainable fashion option.",
    "Choose a water-efficient dishwasher.",
    "Support wildlife conservation programs.",
    "Choose a reusable food wrap instead of plastic wrap.",
    "Reduce car idling time."]

def tasks():
    today = datetime.date.today()
    random.seed(today.year + today.month + today.day)

    tlist = random.sample(task_list, 7)
    return tlist[0], tlist[1], tlist[2], tlist[3], tlist[4], tlist[5], tlist[6]

